### PR TITLE
Ability to load firmwares from the filesystem

### PR DESCRIPTION
**Pull request by the-darkvoid**
Inspired by a message you recently posted about BrcmPatchRAM being large in memory due to its plist size.

Added code to load firmwares from the filesystem instead of from the plist configuration.

Order of loading is (where 0930 = vendor id, 0223 is product id and BCM20702A1_001.002.014.1483.1674_v5770 is firmware key)
- /usr/local/share/BrcmPatchRAM/0930_0223.zhx
- /usr/local/share/BrcmPatchRAM/0930_0223.hex
- /usr/local/share/BrcmPatchRAM/BCM20702A1_001.002.014.1483.1674_v5770.zhx
- /usr/local/share/BrcmPatchRAM/BCM20702A1_001.002.014.1483.1674_v5770.hex

If none of the files are found, it will fall back to the configured firmware in the plist file.

By looking for the firmware using the vendorid / product id, it is easily possible to have custom firmwares without modifying the plist file.

### CODE REVIEW

**Comment by RehabMan** [comment]
Looks interesting.  I'll check it out and test...

**Comment by the-darkvoid** [comment]
I now rewrote the support to use the documented OSKextRequestResource().
This is the same AppleHDA uses to load resources.

This works because we do it against BrcmFirmwareStore which is a fully loaded and started kext.

**Comment by RehabMan** [comment]
Looks good.  After I fixed one problem, I was able to use it for loading a new firmware for my 0a5c:21fb, using Resources/0a5c_21fb.hex.

I also fixed a few other problems: memory leak, concurrency problems (admittedly rare since multiple instances of the BrcmPatchRAM object are rare).

Still need to test the same on 10.11... But my changes are pushed to the fs-firmware branch on my repo.

**Comment by RehabMan** [comment]
This is done.

**Pull request closed without merging**
